name: Build and Push Docker Imag
on:
  push:
    branches:
      - main
      
permissions:
  contents: read    

jobs:
  build_and_push_production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
    
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew
    
      - name: Build JAR file with Gradle
        run: ./gradlew build
        
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          mysql-version: '8.0'
          mysql-database: ${{ secrets.DMYSQL_DATABASE }}
          mysql-user: ${{ secrets.MYSQL_USER }}
          mysql-password: ${{ secrets.MYSQL_PASSWORD }}
          mysql-host: ${{ secrets.MYSQL_HOST }}
      
      - name: Build Docker image for blue
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo-blue:${{ github.run_number }} -t ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo-blue:latest .
        
      - name: Build Docker image for green
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo-green:${{ github.run_number }} -t ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo-green:latest .
      
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Push Docker image for blue
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo-blue:${{ github.run_number }} && docker push ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo-blue:latest

      - name: Push Docker image for green
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo-green:${{ github.run_number }} && docker push ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo-green:latest
          
      - name: Notify Slack on Build Status
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ðŸš€Production Environment Build
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
