name: Build and Push Docker Image
on:
  push:
    branches:
      - main
      
permissions:
  contents: read    

jobs:
  build_and_push_production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
    
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew
    
      - name: Build JAR file with Gradle
        run: ./gradlew build
        
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          mysql-version: '8.0'
          mysql-database: 'db'
          mysql-user: 'root'
          mysql-password: '!skrktkzlWkaQhd123'
          mysql-host: 'db-nlb-839be03d4ed59630.elb.ap-south-1.amazonaws.com' 
      
      - name: Build Docker image for blue
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo:blue .
        
      #- name: Build Docker image for green
        #run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo:green .
      
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Push Docker image for blue
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo:blue
        
      - name: Push Docker image for green
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/rollouts-demo:green
            
      - name: Notify Slack on Build Status (Develop)
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: μΈν”„λΌ_κΉ€μμ§„
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
          message: π€ *Production Environment* Build and Push Docker Image succeeded!
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
